name: Docker Image Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jerray/publish-docker-action@master
      with:
        username: AWS
        password: ${{ secrets.ECR_TOKEN }}
        registry: 932908924219.dkr.ecr.us-east-1.amazonaws.com
        repository: themalwares
        auto_tag: true
